name: Feature Request
description: Suggest an idea for Planify
labels: ["Type: Enhancement"]
body:
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Prerequisites
      options:
        - label: I have searched the [existing issues](https://github.com/alainm23/planify/issues) and this feature has not been requested yet
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      placeholder: "A clear description of the problem. e.g. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      placeholder: Any alternative solutions or workarounds you've tried.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups about the feature request.
    validations:
      required: false
