.TH PLANIFY-QUICK-ADD 1 "2026" "Planify-quick-add 4.18.0" "User Commands"
.SH NAME
planify-quick-add \- Quick adding task to planify wihtout open it
.SH SYNOPSIS
.B planify-quick-add
.RI [ options ]
.SH DESCRIPTION
.PP
Add tasks to Planify without open it simply and quickly!
.SH BUGS
Report bugs on the GitHub issue tracker at:
.PP
.RS
.B https://github.com/alainm23/planify/issues
.RE
.SH AUTHOR
Alain M <alainmh23@gmail.com> and contributors.
.SH SEE ALSO
.BR planify (1)
.BR planify-cli (1)
