/* libgnomeui-2.0.vapi generated by vapigen, do not modify. */

namespace Gnome {
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class App : Gtk.Window, Gtk.Buildable, Atk.Implementor {
		public weak Gtk.AccelGroup accel_group;
		public weak Gtk.Widget contents;
		public weak Gtk.Widget dock;
		public weak Gtk.Widget menubar;
		public weak string name;
		public weak string prefix;
		public weak Gtk.Widget statusbar;
		public weak Gtk.Widget vbox;
		[CCode (has_construct_function = false, type = "GtkWidget*")]
		public App (string appname, string title);
		public void @construct (string appname, string title);
		public void create_menus (Gnome.UIInfo uiinfo);
		public void create_menus_custom (Gnome.UIInfo uiinfo, Gnome.UIBuilderData uibdata);
		public void create_menus_interp (Gnome.UIInfo uiinfo, Gtk.CallbackMarshal relay_func, void* data, GLib.DestroyNotify destroy_func);
		public void create_menus_with_data (Gnome.UIInfo uiinfo);
		public void create_toolbar (Gnome.UIInfo uiinfo);
		public void create_toolbar_custom (Gnome.UIInfo uiinfo, Gnome.UIBuilderData uibdata);
		public void create_toolbar_interp (Gnome.UIInfo uiinfo, Gtk.CallbackMarshal relay_func, void* data, GLib.DestroyNotify destroy_func);
		public void create_toolbar_with_data (Gnome.UIInfo uiinfo);
		public void enable_layout_config (bool enable);
		public static void fill_menu (Gtk.MenuShell menu_shell, Gnome.UIInfo uiinfo, Gtk.AccelGroup accel_group, bool uline_accels, int pos);
		public static void fill_menu_custom (Gtk.MenuShell menu_shell, Gnome.UIInfo uiinfo, Gnome.UIBuilderData uibdata, Gtk.AccelGroup accel_group, bool uline_accels, int pos);
		public static void fill_menu_with_data (Gtk.MenuShell menu_shell, Gnome.UIInfo uiinfo, Gtk.AccelGroup accel_group, bool uline_accels, int pos);
		public static void fill_toolbar (Gtk.Toolbar toolbar, Gnome.UIInfo uiinfo, Gtk.AccelGroup accel_group);
		public static void fill_toolbar_custom (Gtk.Toolbar toolbar, Gnome.UIInfo uiinfo, Gnome.UIBuilderData uibdata, Gtk.AccelGroup accel_group);
		public static void fill_toolbar_with_data (Gtk.Toolbar toolbar, Gnome.UIInfo uiinfo, Gtk.AccelGroup accel_group);
		public static unowned Gtk.Widget find_menu_pos (Gtk.Widget parent, string path, int pos);
		public static unowned string helper_gettext (string str);
		public void insert_menus (string path, Gnome.UIInfo menuinfo);
		public void insert_menus_custom (string path, Gnome.UIInfo uiinfo, Gnome.UIBuilderData uibdata);
		public void insert_menus_interp (string path, Gnome.UIInfo menuinfo, Gtk.CallbackMarshal relay_func, void* data, GLib.DestroyNotify destroy_func);
		public void insert_menus_with_data (string path, Gnome.UIInfo menuinfo, void* data);
		public static void install_appbar_menu_hints (Gnome.AppBar appbar, Gnome.UIInfo uiinfo);
		public void install_menu_hints (Gnome.UIInfo uiinfo);
		public static void install_statusbar_menu_hints (Gtk.Statusbar bar, Gnome.UIInfo uiinfo);
		public void remove_menu_range (string path, int start, int items);
		public void remove_menus (string path, int items);
		public void set_contents (Gtk.Widget contents);
		public void set_menus (Gtk.MenuBar menubar);
		public void set_statusbar (Gtk.Widget statusbar);
		public void set_statusbar_custom (Gtk.Widget container, Gtk.Widget statusbar);
		public void set_toolbar (Gtk.Toolbar toolbar);
		public static void ui_configure_configurable (Gnome.UIInfo uiinfo);
		[NoAccessorMethod]
		public string app_id { owned get; set construct; }
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class AppBar : Gtk.HBox, Gtk.Buildable, Gtk.Orientable, Atk.Implementor {
		[CCode (cname = "gnome_appbar_new", has_construct_function = false, type = "GtkWidget*")]
		public AppBar (bool has_progress, bool has_status, Gnome.PreferencesType interactivity);
		[CCode (cname = "gnome_appbar_clear_stack")]
		public void clear_stack ();
		[CCode (cname = "gnome_appbar_get_progress")]
		public unowned Gtk.ProgressBar get_progress ();
		[CCode (cname = "gnome_appbar_get_response")]
		public unowned string get_response ();
		[CCode (cname = "gnome_appbar_get_status")]
		public unowned Gtk.Widget get_status ();
		[CCode (cname = "gnome_appbar_pop")]
		public void pop ();
		[CCode (cname = "gnome_appbar_push")]
		public void push (string status);
		[CCode (cname = "gnome_appbar_refresh")]
		public void refresh ();
		[CCode (cname = "gnome_appbar_set_default")]
		public void set_default (string default_status);
		[CCode (cname = "gnome_appbar_set_progress_percentage")]
		public void set_progress_percentage (float percentage);
		[CCode (cname = "gnome_appbar_set_prompt")]
		public void set_prompt (string prompt, bool modal);
		[CCode (cname = "gnome_appbar_set_status")]
		public void set_status (string status);
		[NoAccessorMethod]
		public bool has_progress { get; set construct; }
		[NoAccessorMethod]
		public bool has_status { get; set construct; }
		[NoAccessorMethod]
		public Gnome.PreferencesType interactivity { get; set construct; }
		[HasEmitter]
		public virtual signal void clear_prompt ();
		public virtual signal void user_response ();
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	[Compact]
	public class AppBarMsg {
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class Client : Gtk.Object {
		public weak string client_id;
		public weak string clone_command;
		public weak string config_prefix;
		public weak string current_directory;
		public weak string discard_command;
		public weak GLib.HashTable environment;
		public uint fast;
		public weak string global_config_prefix;
		public int input_id;
		public uint interact_style;
		public weak GLib.SList interaction_keys;
		public weak string previous_id;
		public int process_id;
		public weak string program;
		public void* reserved;
		public weak string resign_command;
		public weak string restart_command;
		public Gnome.RestartStyle restart_style;
		public uint save_phase_2_requested;
		public uint save_style;
		public uint save_successfull;
		public uint save_yourself_emitted;
		public uint shutdown;
		public weak string shutdown_command;
		public void* smc_conn;
		public uint state;
		public weak GLib.List static_args;
		public weak string user_id;
		[CCode (has_construct_function = false)]
		public Client ();
		public void add_static_arg ();
		public void flush ();
		public unowned string get_config_prefix ();
		public unowned string get_desktop_id ();
		public Gnome.ClientFlags get_flags ();
		public unowned string get_global_config_prefix ();
		public unowned string get_id ();
		public unowned string get_previous_id ();
		public static unowned Gnome.ModuleInfo module_info_get ();
		public void request_interaction (Gnome.DialogType dialog_type, Gnome.InteractFunction function, void* data);
		public void request_interaction_interp (Gnome.DialogType dialog_type, Gtk.CallbackMarshal function, void* data, GLib.DestroyNotify destroy);
		public void request_phase_2 ();
		public void request_save (Gnome.SaveStyle save_style, bool shutdown, Gnome.InteractStyle interact_style, bool fast, bool global);
		public void save_any_dialog (Gtk.Dialog dialog);
		public void save_error_dialog (Gtk.Dialog dialog);
		public void set_clone_command (int argc, string[] argv);
		public void set_current_directory (string dir);
		public void set_discard_command (int argc, string[] argv);
		public void set_environment (string name, string value);
		public void set_global_config_prefix (string prefix);
		public void set_id (string id);
		public void set_priority (uint priority);
		public void set_process_id (int pid);
		public void set_program (string program);
		public void set_resign_command (int argc, string[] argv);
		public void set_restart_command (int argc, string[] argv);
		public void set_restart_style (Gnome.RestartStyle style);
		public void set_shutdown_command (int argc, string[] argv);
		public void set_user_id (string id);
		[CCode (has_construct_function = false)]
		public Client.without_connection ();
		[HasEmitter]
		public virtual signal void connect (bool restarted);
		public virtual signal void die ();
		[HasEmitter]
		public virtual signal void disconnect ();
		public virtual signal void save_complete ();
		public virtual signal bool save_yourself (int phase, Gnome.SaveStyle save_style, bool shutdown, Gnome.InteractStyle interact_style, bool fast);
		public virtual signal void shutdown_cancelled ();
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class DateEdit : Gtk.HBox, Gtk.Buildable, Gtk.Orientable, Atk.Implementor {
		[CCode (has_construct_function = false, type = "GtkWidget*")]
		public DateEdit (ulong the_time, bool show_time, bool use_24_format);
		public void @construct (ulong the_time, Gnome.DateEditFlags flags);
		[CCode (has_construct_function = false, type = "GtkWidget*")]
		public DateEdit.flags (ulong the_time, Gnome.DateEditFlags flags);
		public int get_flags ();
		public ulong get_initial_time ();
		public ulong get_time ();
		public void set_flags (Gnome.DateEditFlags flags);
		public void set_popup_range (int low_hour, int up_hour);
		public void set_time (ulong the_time);
		[NoAccessorMethod]
		public Gnome.DateEditFlags dateedit_flags { get; set; }
		[NoAccessorMethod]
		public ulong initial_time { get; set; }
		[NoAccessorMethod]
		public int lower_hour { get; set; }
		public ulong time { get; set; }
		[NoAccessorMethod]
		public int upper_hour { get; set; }
		public virtual signal void date_changed ();
		public virtual signal void time_changed ();
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	[Compact]
	public class GdkPixbufAsyncHandle {
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class IconEntry : Gtk.VBox, Gtk.Buildable, Gtk.Orientable, Atk.Implementor {
		[CCode (has_construct_function = false, type = "GtkWidget*")]
		public IconEntry (string history_id, string browse_dialog_title);
		public void @construct (string history_id, string browse_dialog_title);
		public unowned string get_filename ();
		[CCode (cname = "gnome_icon_entry_pick_dialog")]
		public unowned Gtk.Widget get_pick_dialog ();
		public unowned Gtk.Widget gnome_entry ();
		public unowned Gtk.Widget gnome_file_entry ();
		public unowned Gtk.Widget gtk_entry ();
		public void set_browse_dialog_title (string browse_dialog_title);
		public bool set_filename (string filename);
		public void set_history_id (string history_id);
		public void set_icon (string filename);
		public void set_max_saved (uint max_saved);
		public void set_pixmap_subdir (string subdir);
		[NoAccessorMethod]
		public string browse_dialog_title { owned get; set; }
		public string filename { get; set; }
		[NoAccessorMethod]
		public string history_id { owned get; set; }
		[NoAccessorMethod]
		public Gtk.Dialog pick_dialog { owned get; }
		[NoAccessorMethod]
		public string pixmap_subdir { owned get; set; }
		public virtual signal void browse ();
		public virtual signal void changed ();
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class IconSelection : Gtk.VBox, Gtk.Buildable, Gtk.Orientable, Atk.Implementor {
		[CCode (has_construct_function = false, type = "GtkWidget*")]
		public IconSelection ();
		public void add_defaults ();
		public void add_directory (string dir);
		public void clear (bool not_shown);
		public unowned Gtk.Widget get_box ();
		public unowned Gtk.Widget get_gil ();
		public unowned string get_icon (bool full_path);
		public void select_icon (string filename);
		public void show_icons ();
		public void stop_loading ();
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class PasswordDialog : Gtk.Dialog, Gtk.Buildable, Atk.Implementor {
		public weak Gnome.PasswordDialogDetails details;
		[CCode (has_construct_function = false, type = "GtkWidget*")]
		public PasswordDialog (string dialog_title, string message, string username, string password, bool readonly_username);
		public bool anon_selected ();
		public unowned string get_domain ();
		public unowned string get_new_password ();
		public unowned string get_password ();
		public Gnome.PasswordDialogRemember get_remember ();
		public unowned string get_username ();
		public bool run_and_block ();
		public void set_domain (string domain);
		public void set_new_password (string password);
		public void set_password (string password);
		public void set_password_quality_func (Gnome.PasswordDialogQualityFunc func, void* data, GLib.DestroyNotify dnotify);
		public void set_readonly_domain (bool readonly);
		public void set_readonly_username (bool readonly);
		public void set_remember (Gnome.PasswordDialogRemember remember);
		public void set_show_domain (bool show);
		public void set_show_new_password (bool show);
		public void set_show_new_password_quality (bool show);
		public void set_show_password (bool show);
		public void set_show_remember (bool show_remember);
		public void set_show_username (bool show);
		public void set_show_userpass_buttons (bool show_userpass_buttons);
		public void set_username (string username);
		[NoAccessorMethod]
		public bool anonymous { get; set; }
		public string domain { get; set; }
		[NoAccessorMethod]
		public string message { owned get; set; }
		[NoAccessorMethod]
		public string message_markup { owned get; set; }
		public string new_password { get; set; }
		public string password { get; set; }
		[NoAccessorMethod]
		public bool readonly_domain { get; set; }
		[NoAccessorMethod]
		public bool readonly_username { get; set; }
		[NoAccessorMethod]
		public Gnome.PasswordDialogRemember remember_mode { get; set; }
		[NoAccessorMethod]
		public bool show_domain { get; set; }
		[NoAccessorMethod]
		public bool show_new_password { get; set; }
		[NoAccessorMethod]
		public bool show_new_password_quality { get; set; }
		[NoAccessorMethod]
		public bool show_password { get; set; }
		[NoAccessorMethod]
		public bool show_remember { get; set; }
		[NoAccessorMethod]
		public bool show_username { get; set; }
		[NoAccessorMethod]
		public bool show_userpass_buttons { get; set; }
		public string username { get; set; }
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	[Compact]
	public class PasswordDialogDetails {
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public class ThumbnailFactory : GLib.Object {
		[CCode (has_construct_function = false)]
		public ThumbnailFactory (Gnome.ThumbnailSize size);
		public bool can_thumbnail (string uri, string mime_type, ulong mtime);
		public void create_failed_thumbnail (string uri, ulong mtime);
		public unowned Gdk.Pixbuf generate_thumbnail (string uri, string mime_type);
		public bool has_valid_failed_thumbnail (string uri, ulong mtime);
		public unowned string lookup (string uri, ulong mtime);
		public void save_thumbnail (Gdk.Pixbuf thumbnail, string uri, ulong original_mtime);
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	[Compact]
	public class UIBuilderData {
		public weak Gnome.UISignalConnectFunc connect_func;
		public void* data;
		public weak GLib.DestroyNotify destroy_func;
		public bool is_interp;
		public weak Gtk.CallbackMarshal relay_func;
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	[Compact]
	public class UIInfo {
		public Gdk.ModifierType ac_mods;
		public uint accelerator_key;
		public weak string hint;
		public weak string label;
		public void* moreinfo;
		public void* pixmap_info;
		public Gnome.UIPixmapType pixmap_type;
		public Gnome.UIInfoType type;
		public void* unused_data;
		public void* user_data;
		public weak Gtk.Widget widget;
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_CLIENT_")]
	[Flags]
	public enum ClientFlags {
		IS_CONNECTED,
		RESTARTED,
		RESTORED
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_CLIENT_")]
	public enum ClientState {
		IDLE,
		SAVING_PHASE_1,
		WAITING_FOR_PHASE_2,
		SAVING_PHASE_2,
		FROZEN,
		DISCONNECTED,
		REGISTERING
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_DATE_EDIT_")]
	[Flags]
	public enum DateEditFlags {
		SHOW_TIME,
		@24_HR,
		WEEK_STARTS_ON_MONDAY,
		DISPLAY_SECONDS
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_DIALOG_")]
	public enum DialogType {
		ERROR,
		NORMAL
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_EDGE_")]
	public enum EdgePosition {
		START,
		FINISH,
		OTHER,
		LAST
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_FONT_PICKER_MODE_")]
	public enum FontPickerMode {
		PIXMAP,
		FONT_INFO,
		USER_WIDGET,
		UNKNOWN
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_ICON_LIST_")]
	public enum IconListMode {
		ICONS,
		TEXT_BELOW,
		TEXT_RIGHT
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_ICON_LOOKUP_FLAGS_")]
	[Flags]
	public enum IconLookupFlags {
		NONE,
		EMBEDDING_TEXT,
		SHOW_SMALL_IMAGES_AS_THEMSELVES,
		ALLOW_SVG_AS_THEMSELVES
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_ICON_LOOKUP_RESULT_FLAGS_")]
	[Flags]
	public enum IconLookupResultFlags {
		NONE,
		THUMBNAIL
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_INTERACT_")]
	public enum InteractStyle {
		NONE,
		ERRORS,
		ANY
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_MDI_")]
	public enum MDIMode {
		NOTEBOOK,
		TOPLEVEL,
		MODAL,
		DEFAULT_MODE
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_PASSWORD_DIALOG_REMEMBER_")]
	public enum PasswordDialogRemember {
		NOTHING,
		SESSION,
		FOREVER
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_PREFERENCES_")]
	public enum PreferencesType {
		NEVER,
		USER,
		ALWAYS
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_RESTART_")]
	public enum RestartStyle {
		IF_RUNNING,
		ANYWAY,
		IMMEDIATELY,
		NEVER
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_SAVE_")]
	public enum SaveStyle {
		GLOBAL,
		LOCAL,
		BOTH
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_THUMBNAIL_SIZE_")]
	public enum ThumbnailSize {
		NORMAL,
		LARGE
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_APP_CONFIGURABLE_ITEM_")]
	public enum UIInfoConfigurableTypes {
		NEW,
		OPEN,
		SAVE,
		SAVE_AS,
		REVERT,
		PRINT,
		PRINT_SETUP,
		CLOSE,
		QUIT,
		CUT,
		COPY,
		PASTE,
		CLEAR,
		UNDO,
		REDO,
		FIND,
		FIND_AGAIN,
		REPLACE,
		PROPERTIES,
		PREFERENCES,
		ABOUT,
		SELECT_ALL,
		NEW_WINDOW,
		CLOSE_WINDOW,
		NEW_GAME,
		PAUSE_GAME,
		RESTART_GAME,
		UNDO_MOVE,
		REDO_MOVE,
		HINT,
		SCORES,
		END_GAME
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_APP_UI_")]
	public enum UIInfoType {
		ENDOFINFO,
		ITEM,
		TOGGLEITEM,
		RADIOITEMS,
		SUBTREE,
		SEPARATOR,
		HELP,
		BUILDER_DATA,
		ITEM_CONFIGURABLE,
		SUBTREE_STOCK,
		INCLUDE
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cprefix = "GNOME_APP_PIXMAP_")]
	public enum UIPixmapType {
		NONE,
		STOCK,
		DATA,
		FILENAME
	}
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", has_target = false)]
	public delegate void GdkPixbufDoneCallback (Gnome.GdkPixbufAsyncHandle handle, void* cb_data);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", has_target = false)]
	public delegate void GdkPixbufLoadCallback (Gnome.GdkPixbufAsyncHandle handle, GnomeVFS.Result error, Gdk.Pixbuf pixbuf, void* cb_data);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public delegate void InteractFunction (Gnome.Client client, int key, Gnome.DialogType dialog_type);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public delegate double PasswordDialogQualityFunc (Gnome.PasswordDialog password_dialog, string password);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public delegate void ReplyCallback (int reply);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public delegate void StringCallback (string str);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", has_target = false)]
	public delegate void UISignalConnectFunc (Gnome.UIInfo uiinfo, string signal_name, Gnome.UIBuilderData uibdata);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cname = "LIBGNOMEUI_MODULE")]
	public static Gnome.ModuleInfo libgnomeui_module;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string APP_MENUBAR_NAME;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string APP_TOOLBAR_NAME;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int CANCEL;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string CLIENT_PARAM_SM_CONNECT;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string GNOMEUIINFO_KEY_UIBDATA;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string GNOMEUIINFO_KEY_UIDATA;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_CLEAR;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_CLOSE_WINDOW;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_NEW_WINDOW;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_PAUSE_GAME;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_PRINT_SETUP;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_REDO;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_REDO_MOVE;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_MOD_SAVE_AS;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_NAME_CLEAR;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_NAME_CLOSE_WINDOW;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_NAME_NEW_WINDOW;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int KEY_NAME_PRINT_SETUP;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string LIBGNOMEUI_PARAM_CRASH_DIALOG;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string LIBGNOMEUI_PARAM_DEFAULT_ICON;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string LIBGNOMEUI_PARAM_DISPLAY;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string MESSAGE_BOX_ERROR;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string MESSAGE_BOX_GENERIC;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string MESSAGE_BOX_INFO;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string MESSAGE_BOX_QUESTION;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string MESSAGE_BOX_WARNING;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int NO;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int OK;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int PAD;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int PAD_BIG;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int PAD_SMALL;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string PROPERTY_BOX_DIRTY;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_ABOUT;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_ATTACH;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_AUTHENTICATION;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_BLANK;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_BOOK_BLUE;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_BOOK_GREEN;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_BOOK_OPEN;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_BOOK_RED;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_BOOK_YELLOW;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_LINE_IN;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MAIL;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MAIL_FWD;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MAIL_NEW;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MAIL_RCV;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MAIL_RPL;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MAIL_SND;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MIC;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MIDI;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_MULTIPLE_FILE;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_NOT;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_SCORES;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TABLE_BORDERS;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TABLE_FILL;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TEXT_BULLETED_LIST;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TEXT_INDENT;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TEXT_NUMBERED_LIST;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TEXT_UNINDENT;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TIMER;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TIMER_STOP;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TRASH;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_TRASH_FULL;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const string STOCK_VOLUME;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public const int YES;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static void accelerators_sync ();
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool authentication_manager_dialog_is_visible ();
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static void authentication_manager_init ();
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned Gdk.Pixbuf gdk_pixbuf_new_from_uri (string uri);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned Gnome.GdkPixbufAsyncHandle gdk_pixbuf_new_from_uri_async (string uri, Gnome.GdkPixbufLoadCallback load_callback, Gnome.GdkPixbufDoneCallback done_callback, void* callback_data);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned Gdk.Pixbuf gdk_pixbuf_new_from_uri_at_scale (string uri, int width, int height, bool preserve_aspect_ratio);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static void gdk_pixbuf_new_from_uri_cancel (Gnome.GdkPixbufAsyncHandle handle);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned Gnome.ModuleInfo gtk_module_info_get ();
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool help_display_desktop_on_screen (Gnome.Program program, string doc_id, string file_name, string link_id, Gdk.Screen screen) throws GLib.Error;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool help_display_on_screen (string file_name, string link_id, Gdk.Screen screen) throws GLib.Error;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool help_display_uri_on_screen (string help_uri, Gdk.Screen screen) throws GLib.Error;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool help_display_with_doc_id_on_screen (Gnome.Program program, string doc_id, string file_name, string link_id, Gdk.Screen screen) throws GLib.Error;
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static void ice_init ();
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned string icon_lookup (Gtk.IconTheme icon_theme, Gnome.ThumbnailFactory thumbnail_factory, string file_uri, string custom_icon, GnomeVFS.FileInfo file_info, string mime_type, Gnome.IconLookupFlags flags, Gnome.IconLookupResultFlags _result);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned string icon_lookup_sync (Gtk.IconTheme icon_theme, Gnome.ThumbnailFactory thumbnail_factory, string file_uri, string custom_icon, Gnome.IconLookupFlags flags, Gnome.IconLookupResultFlags _result);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static void interaction_key_return (int key, bool cancel_shutdown);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h", cname = "libgnomeui_module_info_get")]
	public static unowned Gnome.ModuleInfo libgnomeui_module_info_get ();
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned Gnome.Client master_client ();
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool thumbnail_has_uri (Gdk.Pixbuf pixbuf, string uri);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool thumbnail_is_valid (Gdk.Pixbuf pixbuf, string uri, ulong mtime);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned string thumbnail_md5 (string uri);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned string thumbnail_path_for_uri (string uri, Gnome.ThumbnailSize size);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static unowned Gdk.Pixbuf thumbnail_scale_down_pixbuf (Gdk.Pixbuf pixbuf, int dest_width, int dest_height);
	[CCode (cheader_filename = "libgnomeui/libgnomeui.h")]
	public static bool url_show_on_screen (string url, Gdk.Screen screen) throws GLib.Error;
}
