name: Android

on:
  push:
    branches: [ feature/android ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: "Android Builder"
    runs-on: ubuntu-latest
    container:
      image: debian:sid
      options: --env DEBIAN_FRONTEND=noninteractive

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            ca-certificates git curl xz-utils unzip zip \
            python3 python3-pip pkg-config build-essential \
            valac ninja-build cmake \
            libgtk-4-dev libadwaita-1-dev libgtksourceview-5-dev \
            libgee-0.8-dev libjson-glib-dev libsoup-3.0-dev \
            libxml2-dev sqlite3 libsqlite3-dev \
            gettext desktop-file-utils \
            libglib-perl libglib-object-introspection-perl libipc-run-perl \
            libjson-perl libset-scalar-perl libxml-libxml-perl libxml-libxslt-perl \
            gir1.2-appstream \
            openjdk-17-jdk \
            glslc gobject-introspection libglib2.0-dev-bin libxml2-utils \
            sassc sdkmanager

      - name: Clone meson
        run: git clone --depth 1 --branch 1.12.0 https://github.com/mesonbuild/meson/ /opt/meson

      - name: Clone gtk-android-builder (pixiewood)
        run: git clone https://github.com/byquanton/gtk-android-builder /opt/gtk-android-builder

      - name: Clone mini-studio
        run: git clone https://github.com/sp1ritCS/mini-studio /opt/mini-studio

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: sdkmanager --install "ndk;29.0.14206865" "platform-tools" "platforms;android-36" "cmdline-tools;latest"

      - name: Pixiewood prepare
        run: /opt/gtk-android-builder/pixiewood -v prepare -a /opt/mini-studio -s /opt/android-sdk/ --meson /opt/meson/meson.py build-aux/android/io.github.alainm23.planify.xml

      - name: Pixiewood generate
        run: /opt/gtk-android-builder/pixiewood -v generate

      - name: Pixiewood build
        run: /opt/gtk-android-builder/pixiewood -v build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v6
        with:
          name: debug-apk
          path: .pixiewood/android/app/build/outputs/apk/debug/*.apk
