name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  flatpak:
    name: "Flatpak (No Evolution)"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@v7
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: planify.Devel.flatpak
          manifest-path: build-aux/no-evolution.json
          cache-key: flatpak-builder-${{ github.sha }}
